USE bibliothèque;

ALTER TABLE Livre
ADD FOREIGN KEY (id_auteur) REFERENCES Auteur(ID) ON DELETE CASCADE;


ALTER TABLE Emprunt
ADD FOREIGN KEY (id_adherent) REFERENCES Adherent(ID) ON DELETE CASCADE,
ADD FOREIGN KEY (id_livre) REFERENCES Livre(ID) ON DELETE CASCADE;

ALTER TABLE Facture
ADD FOREIGN KEY (id_adherent) REFERENCES Adherent(ID) ON DELETE CASCADE;


