USE bibliotheque;

DROP TABLE IF EXISTS Livre;
DROP TABLE IF EXISTS Auteur;
DROP TABLE IF EXISTS Emprunt;
DROP TABLE IF EXISTS Adherent;
DROP TABLE IF EXISTS Facture;
DROP TABLE IF EXISTS Personnel;

DROP DATABASE IF EXISTS bibliotheque;